title: "afunyun - personal site"
description: "The world owes too much of its slop to me. Sorry."
url: "https://afunyun.github.io"
baseurl: "/aifunyun.github.io"

markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

exclude:
    - README.md
    - LICENSE
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor
    - package.json
    - package-lock.json

author: "afunyun"
email: "personal@afjaun.mozmail.com"

github_username: afunyun
huggingface_username: afunyun
discord_username: afunyun
mailto_name: 'afunyun "Jake"'
mailto_email: personal@afjaun.mozmail.com
